# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: "deploy/helm/mlflow-sharinghub/templates"
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        args: [--rev-range, HEAD]
        stages: [push]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.18
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint-fix
        args: [--disable=MD013]
      - id: markdownlint
        args: [--disable=MD013]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: [--failure-threshold=warning, --ignore=DL3008]

  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff format (python)
        entry: ruff format
        files: "^(src|tests)"
        types_or: [python]
        language: python
      - id: ruff-lint
        name: Ruff lint (python)
        entry: ruff check
        args: [--fix, --exit-non-zero-on-fix]
        files: "^(src|tests)"
        types_or: [python]
        language: python
      - id: copyright-header
        name: Copyright header
        entry: ./scripts/copyright.py
        types_or: [python]
        language: python
