apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow-sharinghub.fullname" . }}
  labels:
    {{- include "mlflow-sharinghub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlflow-sharinghub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow-sharinghub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlflow-sharinghub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.mlflowSharinghub.debug }}
          args: [ "mlflow", "server", "--app-name", "sharinghub", "--dev"]
          {{- end }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mlflowSharinghub.existingSecret }}
                  name: {{ .Values.mlflowSharinghub.existingSecret }}
                  {{- else }}
                  name: {{ template "mlflow-sharinghub.fullname" . }}
                  {{- end }}
                  key: secret-key
            - name: MLFLOW_HOST
              value: {{ .Values.mlflowSharinghub.host | quote }}
            - name: MLFLOW_PORT
              value: {{ .Values.service.port | quote }}
            - name: MLFLOW_WORKERS
              value: {{ .Values.mlflowSharinghub.worker | quote }}
            {{- if .Values.postgresql.enabled }}
            - name: MLFLOW_BACKEND_STORE_URI
              {{- if .Values.postgresql.auth.existingSecret }}
              values: {{ printf "postgresql://%s:$POSTGRES_PASSWORD@%s:5432/%s" .Values.postgresql.auth.username (include "postgresql.host" .) .Values.postgresql.auth.database }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}
              {{- else }}
              value: {{ printf "postgresql://%s:%s@%s:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "postgresql.host" .) .Values.postgresql.auth.database }}
              {{- end }}
            {{- else if .Values.mlflowSharinghub.backendStoreUri }}
            - name: MLFLOW_BACKEND_STORE_URI
              value: {{ .Values.mlflowSharinghub.backendStoreUri | quote }}
            {{- else if .Values.mlflowSharinghub.backendStoreUriSecret }}
            - name: MLFLOW_BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mlflowSharinghub.existingSecret }}
                  name: {{ .Values.mlflowSharinghub.existingSecret }}
                  {{- else }}
                  name: {{ template "mlflow-sharinghub.fullname" . }}
                  {{- end }}
                  key: backend-store-uri
            {{- end }}
            {{- if .Values.mlflowSharinghub.artifactsDestination }}
            - name: MLFLOW_ARTIFACTS_DESTINATION
              value: {{ .Values.mlflowSharinghub.artifactsDestination | quote }}
            {{- end }}
            {{- if .Values.s3.enabled }}
            {{- if .Values.s3.endpointUrl }}
            - name: MLFLOW_S3_ENDPOINT_URL
              value: {{ .Values.s3.endpointUrl | quote }}
            {{- end }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  {{- if .Values.s3.existingSecret }}
                  name: {{ .Values.s3.existingSecret }}
                  {{- else }}
                  name: {{ template "mlflow-sharinghub.fullname" . }}-s3
                  {{- end }}
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.s3.existingSecret }}
                  name: {{ .Values.s3.existingSecret }}
                  {{- else }}
                  name: {{ template "mlflow-sharinghub.fullname" . }}-s3
                  {{- end }}
                  key: secret-access-key
            {{- end }}
            - name: LOGIN_AUTO_REDIRECT
              value: "{{ .Values.mlflowSharinghub.loginAutoRedirect }}"
            {{- if .Values.mlflowSharinghub.sharinghubUrl }}
            - name: SHARINGHUB_URL
              value: {{ .Values.mlflowSharinghub.sharinghubUrl | quote }}
            {{- if .Values.mlflowSharinghub.sharinghubStacCollection }}
            - name: SHARINGHUB_STAC_COLLECTION
              value: {{ .Values.mlflowSharinghub.sharinghubStacCollection | quote }}
            {{- end }}
            - name: SHARINGHUB_AUTH_DEFAULT_TOKEN
              value: "{{ .Values.mlflowSharinghub.sharinghubAuthDefaultToken }}"
            {{- end }}
            {{- if .Values.mlflowSharinghub.gitlabUrl }}
            - name: GITLAB_URL
              value: {{ .Values.mlflowSharinghub.gitlabUrl | quote }}
            - name: GITLAB_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ template "mlflow-sharinghub.fullname" . }}-gitlab
                  key: client-id
            - name: GITLAB_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mlflowSharinghub.gitlabOauthExistingSecret }}
                  name: {{ .Values.mlflowSharinghub.gitlabOauthExistingSecret }}
                  {{- else }}
                  name: {{ template "mlflow-sharinghub.fullname" . }}-gitlab
                  {{- end }}
                  key: client-secret
            - name: GITLAB_MANDATORY_TOPICS
              value: {{ .Values.mlflowSharinghub.gitlabMandatoryTopics | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if or .Values.persistence.enabled .Values.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: store
              mountPath: {{ .Values.persistence.mountPath }}
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath | quote }}
              {{- end }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 5000
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.persistence.enabled .Values.extraVolumes }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: store
          persistentVolumeClaim:
            {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "mlflow-sharinghub.fullname" . }}-store-pvc
            {{- end }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
