{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mlflow-sharinghub.fullname" . }}-store-pvc
{{- with .Values.persistence.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote}}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote}}
{{- end }}
